# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171119_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
